# Dockerfile para la aplicación web
# Utilizamos PHP con Apache como base para ejecutar la aplicación
FROM php:8.1-apache

# Instalamos extensiones de PHP necesarias para MySQL
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Creamos el directorio para los logs y establecemos los permisos adecuados
RUN mkdir -p /var/log/php && \
    chown -R www-data:www-data /var/log/php && \
    chmod -R 755 /var/log/php

# Copiamos el código de la aplicación al directorio de trabajo del servidor
COPY ./app/ /var/www/html/

# Establecemos permisos adecuados para los archivos
RUN chown -R www-data:www-data /var/www/html/ && \
    chmod -R 755 /var/www/html/

# Exponemos el puerto 80 para acceder al servidor web
EXPOSE 80

# Comando que se ejecutará cuando se inicie el contenedor
CMD ["apache2-foreground"]